AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create a file share for the given Storage Gateway
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: File Gateway Settings
        Parameters:
          - FileGatewayName
          - StorageGatewayRole
          - StorageGatewayRoleArn
          - FileShareFunction
          - S3Bucket
      - Label:
          default: General Settings
        Parameters:
          - Project
    ParameterLabels:
      FileGatewayName:
        default: 'Storage Gateway Name'
      StorageGatewayRole:
        default: 'Storage Gateway IAM Role'
      StorageGatewayRoleArn:
        default: 'Storage Gateway IAM Role Arn'
      FileShareFunction:
        default: 'Lambda function to create file share'
      S3Bucket:
        default: 'Shared S3 Bucket'
        
Parameters:
  FileGatewayName:
    Type: String
    AllowedPattern: '^[a-zA-Z0-9_-]+$'
    Description: File share will be attached to this Storage Gateway ID
    Default: '-File-Gateway'
  StorageGatewayRole:
    Type: String
    Description: 'IAM role assigned to Storage Gateway'
  StorageGatewayRoleArn:
    Type: String
    Description: 'IAM role Arn assigned to Storage Gateway'
  FileShareFunction:
    Description: 'Lambda function to create file share'
    Type: String
  S3Bucket:
    Description: S3 bucket to share via File Gateway
    Type: String
    Default: MyBucket
  Project:
    Description: Tag used for billing and resource groups
    Type: String
    Default: POC    

Resources:
  StorageGatewayS3AccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !Ref StorageGatewayRole
      PolicyName: !Join
        - '-'
        - - !Ref Project
          - !Ref S3Bucket
          - 'AccessPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetAccelerateConfiguration'
              - 's3:GetBucketLocation'
              - 's3:GetBucketVersioning'
              - 's3:ListBucket'
              - 's3:ListBucketVersions'
              - 's3:ListBucketMultipartUploads'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:GetObjectVersion'
              - 's3:ListMultipartUploadParts'
              - 's3:PutObject'
              - 's3:PutObjectAcl'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
  FileShare:
    DependsOn: StorageGatewayS3AccessPolicy
    Type: Custom::FGWFileShare
    Properties:
      ServiceToken: !Ref FileShareFunction
      GatewayName: !Ref FileGatewayName
      RoleARN: !Ref StorageGatewayRoleArn
      FileShareBucket: !Ref S3Bucket
      StackName: !Ref 'AWS::StackName'
 
Outputs:
  SharedS3Bucket:
    Value: !Ref S3Bucket
    Description: 'S3 Bucket shared by Storage Gateway'
  FileShare:
    Value: !Ref FileShare
    Description: 'FileShare on Storage Gateway'
  FileShareId:
    Value: !GetAtt FileShare.FileShareId
    Description: 'FileShare Id on Storage Gateway'
  NetworkShare:
    Value: !GetAtt FileShare.NetworkShare
    Description: Windows share command to access FileShare