AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template deploys the stack that includes standing up a File Gateway and the related lambda's
Parameters:
  VPCID:
    Description: VPC ID for Storage Gateway
    Type: AWS::EC2::VPC::Id
  Project:
    Description: Tag used for billing and resource groups
    Type: String
  existingSubnet:
    Description: >-
      Subnet to deploy Storage Gateway (prefer private subnet 
      in AZ with EC2 instances)
    Type: 'AWS::EC2::Subnet::Id'
  sgDomainMembers:
    Description: 'Security group ID of domain members (EC2 instances) with access to this Storage Gateway'
    Type: 'AWS::EC2::SecurityGroup::Id'
  instanceType:
    AllowedValues:
      - m5.xlarge
    Default: m5.xlarge
    Type: String
  volumeType:
    Description: 'Choose gp2 (general purpose), io1 (provisioned IOPS), or st1 (throughput optimized HDD)'
    Default: gp2
    Type: String
    AllowedValues:
      - gp2
      - io1
      - st1
  cacheSize:
    Description: '(GiB), Minimum 150 GiB'
    Default: 150
    Type: Number
    MinValue: 150
  provisionedIOPS:
    Description: 'Disk cache IOPS range of 100 to 16000'
    Default: 1000
    Type: Number
    MinValue: 100
    MaxValue: 16000
  DomainAdminUser:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: Admin
    Description: User name for the account that will be added as Domain Administrator.
      This is separate from the default "Administrator" account
    MaxLength: '25'
    MinLength: '5'
    Type: String
  DomainAdminPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: Password for the domain admin user. Must be at least 8 characters
      containing letters, numbers and symbols
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9]+\..+'
    Default: example.com
    Description: Fully qualified domain name (FQDN) of the forest root domain e.g.
      example.com
    MaxLength: '255'
    MinLength: '2'
    Type: String
  CloudFormationBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: CloudFormation assets bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: my-cfn-bucket
    Description: S3 bucket name for the CloudFormation assets. CloudFormation assets bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  CloudFormationKeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: CloudFormation assets key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: my-cfn-key/
    Description: S3 key prefix for the CloudFormation assets. CloudFormation assets key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  LambdaFunctionS3Key:
    Type: String
    Default: my-cfn-key/sgw/fgw-fileshare.zip
    Description: S3 key (path and file name) of the Lambda 'zip' archive.
  Boto3LayerS3Key:
    Type: String
    Default: my-cfn-key/sgw/boto3-layer.zip
    Description: S3 key (path and file name) of the Boto3 SDK 'zip' archive.
  SharedAssetsBucket:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Shared Assets bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: my-assets-bucket
    Description: S3 bucket name for the shared assets. Shared Assets bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String

Resources:
  SGWStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}sgw/sgw.yaml'
      Parameters:
        VPCID: !Ref 'VPCID'
        Project: !Ref 'Project'
        existingSubnet: !Ref 'existingSubnet'
        sgDomainMembers: !Ref 'sgDomainMembers'
        instanceType: !Ref 'instanceType'
        volumeType: !Ref 'volumeType'
        cacheSize: !Ref 'cacheSize'
        provisionedIOPS: !Ref 'provisionedIOPS'
        DomainDNSName: !Ref 'DomainDNSName'
        DomainAdminUser: !Ref DomainAdminUser
        DomainAdminPassword: !Ref 'DomainAdminPassword'
  SGWFileShareFunctionStack:
    DependsOn: SGWStack    
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}sgw/sgw-fileshare-function.yaml'
      Parameters:
        Project: !Ref 'Project'
        LambdaCodeS3Bucket: !Ref 'CloudFormationBucketName'
        LambdaFunctionS3Key: !Ref 'LambdaFunctionS3Key'
        Boto3LayerS3Key: !Ref 'Boto3LayerS3Key'
  SGWFileShareStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}sgw/sgw-fileshare.yaml'
      Parameters:
        Project: !Ref 'Project'
        FileGatewayName: !GetAtt 'SGWStack.Outputs.StorageGatewayName'
        StorageGatewayRole: !GetAtt 'SGWStack.Outputs.StorageGatewayRole'
        StorageGatewayRoleArn: !GetAtt 'SGWStack.Outputs.StorageGatewayRoleArn'
        FileShareFunction: !GetAtt 'SGWFileShareFunctionStack.Outputs.FileShareFunctionARN'
        S3Bucket: !Ref SharedAssetsBucket
  SGWRefreshCacheStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${CloudFormationBucketName}.s3.amazonaws.com/${CloudFormationKeyPrefix}sgw/fileshare-refresh-schedule.yaml'
      Parameters:
        FileGatewayShare: !GetAtt 'SGWFileShareStack.Outputs.FileShareId'
        Project: !Ref 'Project'
Outputs:
  FileGatewayName:
    Value: !GetAtt 'SGWStack.Outputs.StorageGatewayName'
    Description: File Gateway Name
  StorageGatewayRole: 
    Value: !GetAtt 'SGWStack.Outputs.StorageGatewayRole'
    Description: Storage Gateway Role
  StorageGatewayRoleArn:
    Value: !GetAtt 'SGWStack.Outputs.StorageGatewayRoleArn'
    Description: Storage Gateway Role ARN
  FileShareFunction:
    Value: !GetAtt 'SGWFileShareFunctionStack.Outputs.FileShareFunctionARN'
    Description: File Share Function ARN
  FileGatewayShare: 
    Value: !GetAtt 'SGWFileShareStack.Outputs.FileShareId'
    Description: File Gateway Share ID
  NetworkShare:
    Value: !GetAtt 'SGWFileShareStack.Outputs.NetworkShare'
    Description: Network Share Mapping
