AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create an FSx DNS NAME for Windows file system. [v1.0]
Parameters:
  FSxFileSystemID:
    Description: ID for the FSx Filesystem
    Type: String
  Project:
    Description: Tag used for resources and billing
    Type: String
    Default: cloud-edit-fsx
  CloudFormationBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: >-
      CloudFormation assets bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: my-cfn-bucket
    Description: >-
      S3 bucket name for the CloudFormation assets. The bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  LambdaFunctionS3Key:
    Type: String
    Default: cfn-repo/sgw/fsx-dns-name.zip
    Description: S3 key (path and file name) of the Lambda 'zip' archive.
  Boto3LayerS3Key:
    Type: String
    Default: cfn-repo/sgw/boto3-layer.zip
    Description: S3 key (path and file name) of the Boto3 SDK 'zip' archive.

Resources:
  FSxDNSNameLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${Project}-FSxDNSNameLambdaRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'    
      Path: /
  FSxDNSNameLambdaExecutionPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub '${Project}-FSxDNSNamePolicy'
      Roles:
        - !Ref FSxDNSNameLambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: 'arn:aws:iam::*:role/*'
          - Effect: Allow
            Action:
              - 'lambda:AddPermission'
              - 'lambda:RemovePermission'
            Resource: '*'
          - Effect: Allow
            Action: 'fsx:DescribeFileSystems'
            Resource: 'arn:aws:fsx:*:*:*'
          - Effect: Allow
            Action:
              - 'events:PutRule'
              - 'events:DeleteRule'
              - 'events:PutTargets'
              - 'events:RemoveTargets'
            Resource: 'arn:aws:events:*:*:rule/*'
  Boto3Layer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes: 
        - python3.7
        - python3.8
      Content: 
        S3Bucket: !Ref CloudFormationBucketName
        S3Key: !Ref Boto3LayerS3Key
      Description: 'Boto3 SDK layer' 
      LayerName: !Sub '${Project}-FSx-Boto3'
  FSxDNSNameLambda:
    DependsOn: FSxDNSNameLambdaExecutionRole
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${Project}-FSxDNSNameLambda'
      Description: Get FSx DNS Name (file_system_id)
      Runtime: python3.8
      Code:
        S3Bucket: !Ref CloudFormationBucketName
        S3Key: !Ref LambdaFunctionS3Key
      Layers:
        - !Ref Boto3Layer
      Environment: {}
      Handler: fsx-dns-name.handler
      MemorySize: 256
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${FSxDNSNameLambdaExecutionRole}'
      Timeout: 30
  FSxDNSName:
    DependsOn: FSxDNSNameLambdaExecutionPolicy
    Type: Custom::FSxDNSName
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FSxDNSNameLambda}'    
      FileSystemId: !Sub '${FSxFileSystemID}'

Outputs:
  FSxNetworkShare:
    Description: 'The Network Share Mapping for the FSX FileSystem Created'
    Value: !Sub '\\${FSxDNSName.FSxDNSName}\share'
